In [1]:
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Create numpy array from python list

In [3]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [4]:
np.array([2.1,3.2,4.3], dtype="float32")

array([2.1, 3.2, 4.3], dtype=float32)

In [5]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3],[2,3,4]])
type(a2)

numpy.ndarray

In [7]:
a2.shape

(2, 3)

In [8]:
a2.ndim

2

In [9]:
a2.dtype

dtype('int64')

In [10]:
a2.size

6

create numpy array from scratch

zeros, ones, full, arrange, linspace

In [11]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones([3,3], dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.arange(0,20,2, dtype = int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.full([3,3], 6.9)

array([[6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Random

In [16]:
#Seed
np.random.seed(0)

In [17]:
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [18]:
np.random.normal(0,1,[3,3])

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [19]:
np.random.randint(0,10,[4,4])

array([[7, 2, 0, 0],
       [4, 5, 5, 6],
       [8, 4, 1, 4],
       [9, 8, 1, 1]])

In [20]:
np.random.rand(4,4)

array([[0.09928035, 0.96980907, 0.65314004, 0.17090959],
       [0.35815217, 0.75068614, 0.60783067, 0.32504723],
       [0.03842543, 0.63427406, 0.95894927, 0.65279032],
       [0.63505887, 0.99529957, 0.58185033, 0.41436859]])

array indexing and slicing

In [21]:
x1 = np.random.randint(20, size=6)
x1

array([ 3, 15, 13, 16, 17,  5])

In [22]:
x1[1],x1[2]

(15, 13)

multi-dimensional array

In [23]:
x2 = np.random.randint(10, size=(3,4))
print(x2)

[[9 3 0 5]
 [0 1 2 4]
 [2 0 3 2]]


In [24]:
x2[1,2]

2

Slicing

In [25]:
x1

array([ 3, 15, 13, 16, 17,  5])

In [26]:
x1[0:3]

array([ 3, 15, 13])

In [27]:
#every other element , every 2 step
x1[::2]

array([ 3, 13, 17])

In [28]:
x2

array([[9, 3, 0, 5],
       [0, 1, 2, 4],
       [2, 0, 3, 2]])

In [29]:
#two row, three colums
x2[:2,:3]

array([[9, 3, 0],
       [0, 1, 2]])

Reshape of Arrays & Transpose

In [30]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#Transpose
x = np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [33]:
x.T

array([[1., 3.],
       [2., 4.]])

Array concatnation and Spliting

In [34]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [35]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.concatenate((grid,grid)) #axis = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
np.concatenate((grid,grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [38]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])


In [39]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [40]:
#horizontally stack the arrays : hstack
y = np.array([[99],[99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

Spliting array

In [41]:
x = np.array([1,2,3,99,69,3,2,1])

x1,x2,x3 = np.split(x,[3,5])


In [42]:
x1

array([1, 2, 3])

In [43]:
x2

array([99, 69])

In [44]:
x3

array([3, 2, 1])

broadcasting and vectorized operations

In [45]:
a = np.arange(3)
a

array([0, 1, 2])

In [46]:
a+5 #broadcasting

array([5, 6, 7])

In [47]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
a.shape, b.shape

((3,), (3, 3))

In [49]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [50]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [51]:
c = np.arange(3).reshape([3,1])
c

array([[0],
       [1],
       [2]])

In [52]:
c+a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Manipulating and Comparing arrays

Aggegation

In [53]:
list_number = [1,2,3]
ll = np.array(list_number)
ll

array([1, 2, 3])

In [54]:
sum(ll)

6

In [55]:
np.sum(ll)

6

In [56]:
#create a massive Numpy array
massive_array = np.random.random(10000)
massive_array[:10]

array([0.50962438, 0.05571469, 0.45115921, 0.01998767, 0.44171092,
       0.97958673, 0.35944446, 0.48089353, 0.68866118, 0.88047589])

In [58]:
massive_array.shape

(10000,)

In [59]:
%timeit sum(massive_array) #python built-in function in python

761 µs ± 97.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [60]:
%timeit np.sum(massive_array) #Numpy's np.sum()

5.09 µs ± 53.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Statistic

Standard Deviation And Variance(Độ lệch chuẩn và Phương sai)

In [62]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)

np.std(dog_height) #do lech chuan

147.32277488562318

In [63]:
np.var(dog_height) #phuong sai

21704.0

In [64]:
np.mean(dog_height)

394.0

Sorting Arrays



In [66]:
x = np.array([2,1,3,4,5])

np.sort(x)

array([1, 2, 3, 4, 5])

In [67]:
np.argsort(x)

array([1, 0, 2, 3, 4])

Sorting along row or columns

In [68]:
np.random.seed(42)
MatA = np.random.randint(0,10, size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [69]:
np.sort(MatA, axis=0) #sort() theo cot

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [70]:
np.sort(MatA, axis=1) #sort theo hang

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

Linear Algebra : Dai so tuyen tinh

In [73]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [72]:
B = np.array([[6,5],
             [4,3],
             [2,1]])

In [ ]:
#A (3x3) dot product B (3x2)

In [74]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [75]:
C = np.array([[4,1,2],
              [5,6,4],
              [4,2,7],
              [1,8,2]])

In [76]:
D = np.array([[2,1],
              [5,6],
              [7,8]])

In [78]:
C.dot(D)

array([[27, 26],
       [68, 73],
       [67, 72],
       [56, 65]])

Dot product example


In [80]:
#number of jars sold
np.random.seed(0)

sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [81]:
#create weekly_sale dataframe
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts , index=["Mon","Tues","Wed","Thurs","Fri"],
                            columns=["Almon Butter", "Peanut Butter","Cashew Butter"])
weekly_sales

Almon Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thurs             4              6             12
Fri               1              6              7

In [82]:
#create  a price array
prices = np.array([10,8,12])
prices.shape

(3,)

In [84]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"],
                             columns=["Almon Butter", "Peanut Butter","Cashew Butter"])
butter_prices

Almon Butter  Peanut Butter  Cashew Butter
Price            10              8             12

In [85]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [87]:
total_price = weekly_sales.dot(butter_prices.T)
total_price

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [88]:
weekly_sales["Total_Price"] = total_price
weekly_sales

Almon Butter  Peanut Butter  Cashew Butter  Total_Price
Mon              12             15              0          240
Tues              3              3              7          138
Wed               9             19             18          458
Thurs             4              6             12          232
Fri               1              6              7          142